# 模型基本信息
name: isolated_test_model
version: 1.0.0
description: 这是一个在隔离环境中运行的测试模型

# 启用环境隔离
isolation:
  enabled: true
  python_version: "3.10"
  resources:
    memory: "512M"
    cpu: 1

# 模型参数
parameters:
  test_delay: 0.5  # 测试延迟时间（秒）

# 其他设置
settings:
  debug_mode: true 